### ISSUE TITLE
AndroidRuntime: Caused by: java.lang.RuntimeException: Unknown exception code: 47 msg null

### ISSUE THREAD

**Issue by webgenius-coder** [YancyGitHub/native-service#1]
--------- beginning of crash
02-27 21:07:58.507  3401  3401 E AndroidRuntime: FATAL EXCEPTION: main
02-27 21:07:58.507  3401  3401 E AndroidRuntime: Process: com.symbol.demosettings, PID: 3401
02-27 21:07:58.507  3401  3401 E AndroidRuntime: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.wifi.WIFI_STATE_CHANGED flg=0x4000010 (has extras) } in com.symbol.demosettings.SettingsActivity$GeneralPreferenceFragment$1@4f51a41
02-27 21:07:58.507  3401  3401 E AndroidRuntime:    at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52497(LoadedApk.java:1323)
02-27 21:07:58.507  3401  3401 E AndroidRuntime:    at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.$m$7(Unknown Source:4)
02-27 21:07:58.507  3401  3401 E AndroidRuntime:    at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.run(Unknown Source:39)
02-27 21:07:58.507  3401  3401 E AndroidRuntime:    at android.os.Handler.handleCallback(Handler.java:790)
02-27 21:07:58.507  3401  3401 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:99)
02-27 21:07:58.507  3401  3401 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:164)
02-27 21:07:58.507  3401  3401 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:6501)
02-27 21:07:58.507  3401  3401 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
02-27 21:07:58.507  3401  3401 E AndroidRuntime:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
02-27 21:07:58.507  3401  3401 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
02-27 21:07:58.507  3401  3401 E AndroidRuntime: Caused by: java.lang.RuntimeException: Unknown exception code: 47 msg null
02-27 21:07:58.507  3401  3401 E AndroidRuntime:    at android.os.Parcel.readException(Parcel.java:2020)
02-27 21:07:58.507  3401  3401 E AndroidRuntime:    at android.os.Parcel.readException(Parcel.java:1950)
02-27 21:07:58.507  3401  3401 E AndroidRuntime:    at yancy.github.nativeservice.IDemoService$Stub$Proxy.AddNumber(IDemoService.java:97)
02-27 21:07:58.507  3401  3401 E AndroidRuntime:    at com.symbol.demosettings.SettingsActivity$GeneralPreferenceFragment.bindDemoService(SettingsActivity.java:576)
02-27 21:07:58.507  3401  3401 E AndroidRuntime:    at com.symbol.demosettings.SettingsActivity$GeneralPreferenceFragment.-wrap1(Unknown Source:0)
02-27 21:07:58.507  3401  3401 E AndroidRuntime:    at com.symbol.demosettings.SettingsActivity$GeneralPreferenceFragment$1.onReceive(SettingsActivity.java:377)
02-27 21:07:58.507  3401  3401 E AndroidRuntime:    at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52497(LoadedApk.java:1313)
02-27 21:07:58.507  3401  3401 E AndroidRuntime:    ... 9 more
02-27 21:07:58.511  1585  1604 W ActivityManager:   Force finishing activity com.symbol.demosettings/.SettingsActivity

private BroadcastReceiver WifiStateChangedReceiver = new BroadcastReceiver() {
    @Override
    public void onReceive(Context context, Intent intent) {
        int extraWifiState = intent.getIntExtra(WifiManager.EXTRA_WIFI_STATE ,
                                                WifiManager.WIFI_STATE_UNKNOWN);
        switch (extraWifiState) {
        case WifiManager.WIFI_STATE_ENABLED:
            bindDemoService();
            break;
        case WifiManager.WIFI_STATE_ENABLING:
            break;
        case WifiManager.WIFI_STATE_UNKNOWN:
            break;
        }
    }
};

private void bindDemoService() {
    try {
        IBinder b = ServiceManager.getService("yancy.github.nativeservice.IDemoService");
        if(b != null) {
            final IDemoService service =
                    IDemoService.Stub.asInterface(b);
            if(service != null) {
                Log.d("DEMOSERVICE", "AddNumber(23, 24): " + service.AddNumber(1, 2));
                Log.d("DEMOSERVICE", "MaxNumber(23, 24): " + service.MaxNumber(10, 11));
                Log.d("DEMOSERVICE", "MaxNumber(33, 24): " + service.MaxNumber(20, 21));
            } else {
                Log.d("DEMOSERVICE", "MainActivity asInterface fail.");
            }
        } else {
            Log.d("DEMOSERVICE", "MainActivity get native service fail.");
        }
    } catch(RemoteException e) {
        Log.d("DEMOSERVICE", "ERROR:" + e.getMessage());
    }
}

**Comment by YancyGitHub** [comment]
IDemoService.cpp , BpDemoService：
**+ reply.readExceptionCode();**
return reply.readInt32();

**+ reply->writeNoException();**
reply->writeInt32(ret);

**Comment by YancyGitHub** [comment]
Fix By: 1fc0b62162
Fix android L native service bug
