### ISSUE TITLE
How compile Service

### ISSUE THREAD

**Issue by lahed** [YancyGitHub/native-service#4]
Hey, very good example!

How can I compile without AOSP?

Thank you!

**Comment by YancyGitHub** [comment]
This example cannot be compiled in a non-AOSP environment. The code is based on AOSP and depends on part of the AOSP code. You can use NDK Binder to develop your own programs。
https://developer.android.google.cn/ndk/reference/group/ndk-binder

**Comment by lahed** [comment]
oh, I have an error with aosp

source build/envsetup.sh
lunch 6 (?)
cd external/native-service/android_L/service
mm

and I get

```
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=6.0
TARGET_PRODUCT=full
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=
TARGET_2ND_ARCH_VARIANT=
TARGET_2ND_CPU_VARIANT=
HOST_ARCH=x86_64
HOST_OS=darwin
HOST_OS_EXTRA=Darwin-17.7.0-x86_64-i386-64bit
HOST_BUILD_TYPE=release
BUILD_ID=MRA58K
OUT_DIR=out
============================================
make: *** No rule to make target `out/target/product/generic/obj/lib/crtbegin_dynamic.o', needed by `out/target/product/generic/obj/EXECUTABLES/DemoService_intermediates/LINKED/DemoService'.  Stop.
```

**Comment by lahed** [comment]
@YancyGitHub  I was able to compile download AOSP again :D

But I have a problem, I created a java application and connected it with the service c++. It worked perfect.

I tried the same from real device but binder is null, the service is running as root. Do you know, or do we have to do something else?

Thank you!

**Comment by Reversive** [comment]
I have the same problem, if I compile the service and the client as c++ i can run it in my android 8.0 (Oreo, with SELinux Enforcing and KNOX) just fine but if i try to use JAVA as my client the binder returns null.

**Comment by lahed** [comment]
Fixed with magiskpolicy !

**Comment by lahed** [comment]
Other problem 💀 found binder but "android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died"

**Comment by lahed** [comment]
Fixed with magiskpolicy
